### ISSUE TITLE
typo in azure_terraform_blueprint_aks/application_gateway/main.tf

### ISSUE THREAD

**Issue by herveleclerc** [LaurentLesle/azure_terraform_blueprint_aks#17]
helthz should be healthz

**Comment by LaurentLesle** [comment]
Thanks @herveleclerc for reporting the issue. It is now fixed.
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/4702224/57633373-0fcc2900-75d6-11e9-885f-7c4eb911396b.png">
